### PR TITLE
Add `maintenance_info` field to Service Plan object

### LINKED ISSUE #233: Add `maintenance_info` field to Service Plan object
https://github.com/openservicebrokerapi/servicebroker/blob/master/spec.md#service-plan-object

### PR DESCRIPTION
**Pull request by ilyavy**
Resolves #233

OSB 2.15 adds a maintenance_info field to the Service Plan. Service Brokers can specify optional Maintenance information for a Service Instance which is provisioned using the Service Plan. 

If the value is null, the field will be omitted from the serialized JSON.

I used [Java implementation of the Semantic Versioning Specification](https://github.com/zafarkhaja/jsemver) to make sure that provided version complies to [semantic version 2.0](https://semver.org/spec/v2.0.0.html), as [it described by the specification](https://github.com/openservicebrokerapi/servicebroker/blob/master/spec.md#maintenance-info-object).

### CODE REVIEW

**Comment by ilyavy** [comment]
Thank you for the question! Actually, I thought about it as well but eventually, have chosen a new dependency (although this library does not look like something really finished and well designed). My motivation was the following:
1. Semver 2.0 is more complicated than just MAJOR.MINOR.PATCH, because it can also contain labels for pre-release and build metadata. => That's why I thought that the regex for sermver will need some good testing itself and it will complicate things.
2. I wanted to give users a way to understand that their version provided is wrong in compile time (if Java-based configuration is used for maintenance info).

However, now when you brought the question (which is one of the greatest things of working in team :)), I realized that it was a bad decision after all. For the following reasons:
1. The regex already exists and can be found in [semver repository](https://github.com/semver/semver/issues/232). People have tested it, so it's probably safe to use it. (Also there is a [Backus-Naur Form Grammar](https://github.com/semver/semver/blob/master/semver.md#backusnaur-form-grammar-for-valid-semver-versions) in the spec, but I don't know about the ways to automatically convert it into regex.)
2. A lot of people use YAML configurations and in this case, the version will be parsed from the string anyway. So if the version does not comply to semver 2.0 users will know about it at runtime anyway.

So, concluding, I would like to cut off the dependency and substitute it with the [regex](https://github.com/semver/semver/issues/232). What do you think?

**Comment by royclarkson** [comment]
Thanks for the detailed response! I'm not against adding dependencies if they add significant value, however I think we can handle most of our needs without it in this case.

My initial thoughts are that the version can be stored as a `String`. The setter in the model object should accept a string and validate it via a regex. If it doesn't validate, then throw an exception (maybe IllegalArgumentException?). We can also provide a separate convenience setter for java configuration that allows setting the various parts. something like: `setVersion(int major, int minor, int patch, String extension)`. Then we can build the version string from those inputs. How does that sound?

**Comment by ilyavy** [comment]
Sounds great! I changed the code

**Comment by ilyavy** [comment]
Done

**Pull request merged**
