### PR TITLE
Return a 400 status instead of 412 for API version checks

### LINKED ISSUE #217: Incorrect HTTP Response code when the X-Broker-API-Version header doesn't exist
Hi guys!
According to the OSB spec v2.14 https://github.com/openservicebrokerapi/servicebroker/blob/v2.14/spec.md#api-version-header the `X-Broker-API-Version` header is mandatory. It means when any mandatory data is missing service broker must return `400 Bad Request`.

But current implementation in  a method `ApiVersionInterceptor#preHandle` checks only version is equal or not to which implemented by service broker.

### PR DESCRIPTION
**Pull request by royclarkson**
Resolves #217

### CODE REVIEW

**Comment by scottfrederick** [comment]
@royclarkson I don't think this change is the right one. What the [OSB API spec](https://github.com/openservicebrokerapi/servicebroker/blob/v2.14/spec.md#api-version-header) says is:

> In this scenario [the Service Broker's expected version doesn't match the Platform's provided version] the Service Broker MAY reject the request with `412 Precondition Failed`

This behavior should be preserved. 

The case that wasn't being handled is when the `X-Broker-API-Version` header is missing from the request, even though it's required by the spec. The suggestion was that a `400 Bad Request` should be returned in this case.

**Comment by aukhatov** [comment]
Hi @royclarkson, I agree with @scottfrederick about preserving this behavior:
> In this scenario [the Service Broker's expected version doesn't match the Platform's provided version] the Service Broker MAY reject the request with 412 Precondition Failed

In the issue https://github.com/spring-cloud/spring-cloud-open-service-broker/issues/217 I mean about behavior of the response when `X-Broker-API-Version` in the request is missing. Because according to the [OSB spec](https://github.com/openservicebrokerapi/servicebroker/blob/v2.14/spec.md#api-version-header) the status of `412 Precondition Failed` should be returned when the header `X-Broker-API-Version` doesn't match, **but not missing**.

**Comment by royclarkson** [comment]
@aukhatov @scottfrederick thanks for the feedback. I misunderstood the requirement. I'll modify this PR to only return a 400 if the developer has configured a specific version for the service broker AND the header is missing. However, if the header is missing, but there is no version configured, then we'll continue to ignore it as was previously discussed. Do I have the requirement sorted now? :)

**Comment by aukhatov** [comment]
@royclarkson Yes, thank you!
What version do we need to expect?

**Comment by royclarkson** [comment]
Closing in favor of community contribution #219

**Pull request closed without merging**
