### PR TITLE
Adds MaintenanceInfo to CSIReq, UPSIReq and PreviousValues

### LINKED ISSUE #290: maintenance_info is missing from CSIReq, USIReq and error code exception
## Expected behavior

As a service broker author, 
* In order to respond to `cf update-service --upgrade` requests, 
* I need to receive `MaintenanceInfo` in update service instance request (along with previousValue)
* In order to respond to invalid OSB CSI request with invalid maintenance_info
--upgrade` requests, 
* I need to receive `MaintenanceInfo` in create service instance request

## Current behavior

MaintenanceInfo is only available in the plan object

### Background:

Maintenance-info was added in 2.15 spec version see https://github.com/openservicebrokerapi/servicebroker/pull/642/files but poorly documented in [release notes](https://github.com/openservicebrokerapi/servicebroker/blob/master/release-notes.md) as merely

> Added maintenance info support to Service Plans.

#233 and #239 only covered the service plan part, but missed the CSIR,UPSIR and exception

### PR DESCRIPTION
**Pull request by gberche-orange**
Fixes #290

### CODE REVIEW

**Comment by royclarkson** [comment]
@gberche-orange Thanks for the PR! There appears to be a number of cosmetic changes or reordering of class members. Those are making it difficult to see exactly what is changing. Mind backing those out and limiting the PR to the functionality changes?

**Comment by gberche-orange** [comment]
@royclarkson I had to reformat modified classes to fix formatting checks in CI, however, I have made it into a distinct commit with mostly reformatting https://github.com/spring-cloud/spring-cloud-open-service-broker/pull/291/commits/f0bf7312fcc2cc41fadc0850a8c74328886b0369

Would review of the 1st commit https://github.com/spring-cloud/spring-cloud-open-service-broker/pull/291/commits/d61205e48f1137a669e8401513c3927938f65e6b be easier ?

**Comment by royclarkson** [comment]
@gberche-orange yes, that first commit is much better. I can much more easily review it now. Thanks!

**Comment by royclarkson** [comment]
Closed in 576b86f31b89f1c0884d12f65947e01d401388f6

**Comment by gberche-orange** [comment]
thanks @royclarkson !

**Pull request closed without merging**
