### PR TITLE
Fix Json serialization of model objects for use by OSB clients

### PR DESCRIPTION
**Pull request by gberche-orange**
Add some prereqs for supporting an osb client (#77);
- some requests model classes serialize as Json compliant with OSB specs. 
   - covered model classes: Create** Delete**
   - not yet covered model classes: Get** Update**

### CODE REVIEW

**Comment by royclarkson** [comment]
@gberche-orange thanks! would you mind squashing this to a single commit? We'll get it into the next 2.1 milestone.

**Comment by gberche-orange** [comment]
@royclarkson sure, I'll probably add support for Get** and Update** request classes in the next few days and then squash into a single commit. Any deadline set for 2.1 yet I should be aware of ?

**Comment by royclarkson** [comment]
@gberche-orange I need to get another 2.1 prerelease milestone out asap. I may just take what you have here and squash it, then you can submit another PR with additional changes if you don't get to it before I do. Thanks.

**Comment by gberche-orange** [comment]
@royclarkson @scottfrederick please review the squashed commit.

I had a hard time with jackson config, trying to meet requirements of existing tests, while adding support for OSB compliant serialization, in particular for the Context class and its inheritance. I did not find a way to completely avoid duplicate Json fields and the Context.platform remains duplicated (see example below). I understand from https://stackoverflow.com/questions/21832701/does-json-syntax-allow-duplicate-keys-in-an-object that this is probably ok for most Json parsers, but some may still break.

```json
{
  "platform": "cloudfoundry",
  "platform": "cloudfoundry",
  "organization_guid": "org-guid",
  "space_guid": "space-guid"
}
```

**Comment by royclarkson** [comment]
@gberche-orange I noticed GitHub says you are a first time contributor to this project and I need to confirm that you have you signed the [Pivotal CLA](https://cla.pivotal.io/sign/spring). Thanks.

**Comment by royclarkson** [comment]
@gberche-orange I'm reviewing the PR now and will look at that specific `Context` serialization case.

**Comment by royclarkson** [comment]
@gberche-orange thanks!

**Comment by royclarkson** [comment]
@gberche-orange I went ahead and released 2.1.0 as is. I'll plan to merge this into the 2.x branch soon and we can release it once we've had a chance to review it a bit more. Thanks again for all your interest in the project!

**Comment by gberche-orange** [comment]
@royclarkson please let me know if you have questions regarding this PR and whether a meeting could help speedup exchanges if some are needed.

I rebased it against 2.x recently, and fixed additional things that broke as a result.

**Comment by gberche-orange** [comment]
@royclarkson ping

**Comment by royclarkson** [comment]
Thanks for this contribution. It's great to see the additional serialization support.

Closed in 5f26afaaff59e37d36ff2a279986c31b6e6581ea

**Comment by gberche-orange** [comment]
great, thanks @royclarkson for your review and your merge of this contrib.

**Pull request closed without merging**
